### ISSUE TITLE
Support etcd client TLS

### ISSUE THREAD

**Issue by colhom** [projectcalico/calico-cni#100]
Along with [`etcd_endpoints`](https://github.com/projectcalico/calico-cni/blob/master/configuration.md#etcd-location), there should be fields along the lines of `etcd_cacert`,`etcd_cert`, and `etcd_key` for interacting with client-cert authenticated etcd endpoints.

\cc @tomdee

**Comment by caseydavenport** [comment]
Agreed that CNI network config fields would be nice.

This works at the moment using environment variables as described here: https://github.com/projectcalico/calico-containers/blob/master/docs/EtcdSecureCluster.md#etcd-with-client-and-server-verification

**Comment by caseydavenport** [comment]
#113 adds TLS to the CNI network config file.
