### ISSUE TITLE
NetworkPlugin cni failed on the status hook for pod 'nginx' - invalid CIDR address: Device "eth0" does not exist.

### ISSUE THREAD

**Issue by jonathan-kosgei** [projectcalico/calico-cni#111]
I have the following kubelet error on my minions:
`Jul 02 16:20:42 sc-minion-1 kubelet[46142]: E0702 16:20:42.899902   46142 manager.go:309] NetworkPlugin cni failed on the status hook for pod 'nginx' - invalid CIDR address: Device "eth0" does not exist.`

My 10-calico.conf on all nodes looks like this:
```
{
    "name": "calico-k8s-network",
    "type": "calico",
    "etcd_authority": "172.1.1.4:6666",
    "log_level": "info",
    "ipam": {
        "type": "calico-ipam"
    }
}
```

I also ran: `calicoctl pool add 192.168.0.0/16 --ipip --nat-outgoing` on all nodes.

**Comment by fasaxc** [comment]
@jonathan-kosgei We've seen that error from a known k8s bug, where it queries the state of the pod before the CNI plugin has finished setting it up.  Were there any other symptoms you were seeing; did the pod come up and get networked?

**Comment by jonathan-kosgei** [comment]
@fasaxc Hi, the pod comes up, and I can curl ngin from the node it's been scheduled on. What led to to this however was that I couldn't curl the pod ip or the service ip from across hosts.

**Comment by fasaxc** [comment]
Were you curling from another host or from a pod on another host?  Was the other host running Calico? Do you have any security policy in place that could be blocking the traffic?  Please can you share the output from `ip route` on the host that you were curling from?

**Comment by jonathan-kosgei** [comment]
The two hosts, kubernetes minions have the exact same setup, automated install via ansible. I tried curling from both the host itself and a busybox pod via docker run --rm -it busybox sh; actually wget on the busybox pod. I have port 179 tcp/udp open and calicoctl status is established between the two hosts. Let me just get that for you.

**Comment by jonathan-kosgei** [comment]
On the host I was curling from:
```
root@sc-minion-0:~# ip route
default via 172.1.2.1 dev eth0 
10.0.3.0/24 dev lxcbr0  proto kernel  scope link  src 10.0.3.1 
168.63.129.16 via 172.1.2.1 dev eth0 
172.1.2.0/24 dev eth0  proto kernel  scope link  src 172.1.2.5 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 
192.168.0.1 dev calife2d2bc6404  scope link 
192.168.0.71 via 172.1.2.4 dev tunl0  proto bird onlink 
192.168.1.0/26 via 172.1.2.4 dev tunl0  proto bird onlink 
blackhole 192.168.1.64/26  proto bird 
```
On the host with the nginx pod running:
```
root@sc-minion-1:~# ip route
default via 172.1.2.1 dev eth0 
10.0.3.0/24 dev lxcbr0  proto kernel  scope link  src 10.0.3.1 
168.63.129.16 via 172.1.2.1 dev eth0 
172.1.2.0/24 dev eth0  proto kernel  scope link  src 172.1.2.4 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 
192.168.0.1 via 172.1.2.5 dev tunl0  proto bird onlink 
blackhole 192.168.1.0/26  proto bird 
192.168.1.2 dev cali765599c241a  scope link 
192.168.1.64/26 via 172.1.2.5 dev tunl0  proto bird onlink 
```

**Comment by fasaxc** [comment]
What's the IP of the pod you were accessing?

**Comment by jonathan-kosgei** [comment]
The pod nginx ip is 192.168.1.2, the nginx service ip is 10.254.9.141

**Comment by fasaxc** [comment]
The routing looks correct to me.  Can you try running traceroute to see where the packets are being dropped?  You could also run `tcpdump -nli tunl0` on each host to see how far the packets get; is it the request or response that doesn't make it through? 

Do you have any Calico network policy in place?

**Comment by jonathan-kosgei** [comment]
Not sure what exactly is the calico network policy, I don't have a deep knowledge of networking or running traceroute, I've uploaded the diags to https://transfer.sh/VcSyu/diags-040716-155209.tar.gz maybe that could help, or if you could walk me through.

**Comment by fasaxc** [comment]
@jonathan-kosgei I mean, have you configured any Calico security rules?  We provide networking and a distributed firewall; have you created any firewall rules?

**Comment by jonathan-kosgei** [comment]
@fasaxc No, to my knowledge no, only ports I have open on the nodes are 10250, 179 udp/tcp , 22, 80, 443

**Comment by fasaxc** [comment]
The diags confirm, looks like there's no policy in place.  Where are you running your cluster?  I wonder if the underlying network fabric is blocking IPIP packets.

**Comment by jonathan-kosgei** [comment]
Actually on azure, I had run calicoctl pool add 192.168.0.0/16 --ipip --nat-outgoing on all the nodes

**Comment by fasaxc** [comment]
I think Azure blocks IPIP traffic, which prevents Calico networking from working.

**Comment by fasaxc** [comment]
I believe we're tracking the Azure issue here: https://github.com/projectcalico/calico-containers/issues/949

**Comment by jonathan-kosgei** [comment]
Thanks for the pointer, this sucks though, have to switch to weave or flannel.

**Comment by fasaxc** [comment]
Flannel and Calico are actually merging under the new Canal project so Calico security policy alreayd works with flannel.
