### ISSUE TITLE
How do to make cni plugin work with secure etcd server?

### ISSUE THREAD

**Issue by codefx9** [projectcalico/calico-cni#112]
Hi,
I am trying to configure calico to work as a Kubernetes cni plugin. I am using a secure etcd server with client cert authentication. I am able to configure calicoctl node with Kubernetes. But how do I provide cert, key etc to the cni plugin? I don't see any configuration parameter for that?

https://github.com/projectcalico/calico-cni/blob/master/configuration.md

Reading https://github.com/projectcalico/calico-cni/blob/f2e2cf774646b443f2f9f499e7650b444e0e7bfa/calico.py#L28 , it seems not possible today. Am I right?

**Comment by codefx9** [comment]
It seems it can be added by exporting ENV variables that are ready by pycalico.DatastpreClient https://github.com/projectcalico/libcalico/blob/master/calico_containers/pycalico/datastore.py#L143

Am I right?

**Comment by TamalSaha** [comment]
Hi,
We are also interested in this. I have created a pull request for this: https://github.com/projectcalico/calico-cni/pull/113

**Comment by intlabs** [comment]
Yeah, looks like it's unsupported at the moment.
I'm gonna try the patch TamalSaha's made, as it looks fine to me. Without tls to etcd Calico is a non-starter in our environment.

**Comment by caseydavenport** [comment]
Sorry this isn't more clear in the CNI documentation:

https://github.com/projectcalico/calico-containers/blob/v0.20.0/docs/EtcdSecureCluster.md

The above link discusses environment variables which can be set in the CNI plugin to use TLS.  These can be set in the Kubelet process so they are inherited by the CNI plugin env.

Definitely worth making these explicit configuration parameters in the CNI network config as @TamalSaha has done - will take a look at that PR.

**Comment by caseydavenport** [comment]
Merged #113

**Comment by intlabs** [comment]
Cheers, the documentation could make it clearer for sure. Using env vars is fine for us; and a quick test shows its pretty easy :) Thanks.

**Comment by TamalSaha** [comment]
Thanks a lot @caseydavenport. Any chance that a new release can be cut with this change?

**Comment by caseydavenport** [comment]
@TamalSaha - My plate is pretty full at the moment, so unfortunately I can't make any promises about when this will make it into a release.  I will make an effort to get something out soon if it's possible :)
