### ISSUE TITLE
Sample master manifest is not sensitive to config file contents

### ISSUE THREAD

**Issue by MikeSpreitzer** [projectcalico/calico-cni#117]
... and thus, for example, the apiserver container is not restarted when some of its config files (e.g., its TLS server certificate) changes.

I am referring to, for example, https://github.com/projectcalico/calico-cni/blob/master/samples/kubernetes/master/kubernetes-master.manifest (because http://kubernetes.io/docs/getting-started-guides/ubuntu-calico/ tells me to).

I am using this thing in a code-as-infrastructure paradigm, specifically with an idempotent style of management imposed via Ansible.  After I deploy the master using Ansible, if I later change the contents of the apiserver's TLS certificate, currently the apiserver does not notice the change and nothing restarts the apiserver.

Here is a suggestion for how to fix.  If, for example, a hash of the relevant config file contents appeared in the container spec for the apiserver (e.g., by my Ansible playbook making it so) then the kubelet would automatically restart that container when any of the config file contents change.

**Comment by MikeSpreitzer** [comment]
And it looks like `calicoctl node` is even worse.  When Ansible deploys a new version of `calicoctl`, nothing stops the old running node stuff and starts running the new node stuff.  The node stuff seems to include a service with two processes and also a Docker container.

**Comment by MikeSpreitzer** [comment]
Then again, maybe something did!
```
$ service calico-node status
● calico-node.service - Calico per-node agent
   Loaded: loaded (/etc/systemd/calico-node.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2016-07-08 23:28:38 EDT; 24h ago
     Docs: https://github.com/projectcalico/calico-docker
 Main PID: 9217 (calicoctl)
    Tasks: 2
   Memory: 22.9M
      CPU: 341ms
   CGroup: /system.slice/calico-node.service
           ├─9217 /usr/bin/calicoctl node --ip=100.127.0.2 --detach=false
           └─9219 /usr/bin/calicoctl node --ip=100.127.0.2 --detach=false

Jul 08 23:28:38 mvespa1-2 systemd[1]: calico-node.service: Service hold-off time over, scheduling restart.
Jul 08 23:28:38 mvespa1-2 systemd[1]: Stopped Calico per-node agent.
Jul 08 23:28:38 mvespa1-2 systemd[1]: Started Calico per-node agent.
```

**Comment by MikeSpreitzer** [comment]
Here's another one.   When Ansible updates the CNI plugin's config file, nothing causes the kubelet to re-read it.

**Comment by caseydavenport** [comment]
@MikeSpreitzer good points, thanks for raising.

> When Ansible updates the CNI plugin's config file, nothing causes the kubelet to re-read it.

I think this PR aims to make this better: https://github.com/kubernetes/kubernetes/pull/28178

> If, for example, a hash of the relevant config file contents appeared in the container spec for the apiserver (e.g., by my Ansible playbook making it so) then the kubelet would automatically restart that container

This sounds like it will work to me - you can probably just include the hash as some sort of metadata on the api-server manifest and the kubelet will pick that up.  I'm not sure there are any changes required to this repo for that to work though, right?

> When Ansible deploys a new version of calicoctl, nothing stops the old running node stuff and starts running the new node stuff. 

Yeah, I think you'll need a trigger to re-run the `calicoctl node` command, which will re-start the node container with the updated version.

So, one option would be:
- Download the desired `calicoctl` (e.g 0.20.0)
- Pull the desired node image: `docker pull calico/node:v0.20.0`
- Update the `calicoctl` command to include the image: `calicoctl node --node-image=calico/node:v0.20.0`
- Restart the systemd service.

Another more experimental option would be to try running the `calico/node` container directly under the kubelet or as a DaemonSet.  I _think_ this should work but I haven't done extensive testing.  Happy to help investigate this path.

> The node stuff seems to include a service with two processes and also a Docker container.

I believe it's just a systemd unit which starts the `calico/node` docker container and doesn't detach, allowing systemd to re-start the container if it stops.

**Comment by caseydavenport** [comment]
Samples have since been removed from this repository (new location TBD), and were really just meant as a starting point (not to cover all real deployment scenarios).  Closing for now.
