### ISSUE TITLE
skydns.yaml creates too much at once

### ISSUE THREAD

**Issue by MikeSpreitzer** [projectcalico/calico-cni#118]
https://github.com/projectcalico/calico-cni/blob/master/samples/kubernetes/master/dns/skydns.yaml, referenced from http://kubernetes.io/docs/getting-started-guides/ubuntu-calico/, calls for the creation of three things --- which is a problem if not all three need to be created.  For those of us trying to write idempotent management, this combo is not useful --- we need to automate creation of each individual piece that does not exist yet.

I ran into an instance of this problem when the `kube-system` namespace existed but the skydns RC and service did not.

**Comment by caseydavenport** [comment]
I think the important part here is that v1.3.0 automatically creates the kube-system namespace now, so that file shouldn't be trying to create it.

`kubectl apply -f <file>` should work as an idempotent create/update action.

http://kubernetes.io/docs/user-guide/kubectl/kubectl_apply/
