### ISSUE TITLE
subnet config in cni is not working?

### ISSUE THREAD

**Issue by reAsOn2010** [projectcalico/calico-cni#125]
I have a calico cni config under /etc/cni/net.d
```
{
    "name": "calico-k8s-network",
    "type": "calico",
    "etcd_endpoints": "http://192.168.205.10:2379",
    "log_level": "info",
    "ipam": {
        "type": "calico-ipam",
        "subnet": "192.168.64.0/20"
    }
}
```
But the `subnet` config is of no use, calicoctl pool show:
```
+----------------+---------+
|   IPv4 CIDR    | Options |
+----------------+---------+
| 192.168.0.0/16 |         |
+----------------+---------+
```
And the containers is taking IP from the pool but not the subnet I configured.
Is it working as expected?

**Comment by caseydavenport** [comment]
@reAsOn2010 this is the correct behavior when using the `calico-ipam` plugin.  Calico IPAM automatically chooses blocks from the configured pool as needed.

The `subnet` field applies to the [`host-local` IPAM plugin](https://github.com/containernetworking/cni/tree/master/plugins/ipam/host-local).  If you'd like to statically assign subnets to each node you can do that with this plugin like so:

```json
"type": "calico",
"ipam": {
  "type": "host-local",
  "subnet": "<your subnet>"
}
```

The chosen subnets will still need to fall within the configured Calico pool.

**Comment by reAsOn2010** [comment]
I see~ thanks for reply!
