### ISSUE TITLE
Docker restart causes pods to lose connectivity

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-cni#132]
Looks like Felix doesn't handle the renaming of the host side veth nicely.  See https://github.com/projectcalico/calico/issues/1075

We could work around this by deleting / re-creating the endpoint rather than updating it.

@tomdee are you OK with this as a workaround?  We need to handle this case for the v1.4 release.

**Comment by fasaxc** [comment]
You'd really need to delete and re-add with a different ID to force Felix to do the right thing in all cases.  Given this is causing real problems, I'm inclined to fix Felix (but the workaround might still give a quicker fix).

**Comment by caseydavenport** [comment]
@tomdee and I were just discussing this, and we think that we should be looking to fix this in Felix.  The workarounds required in the CNI plugin would muddle the clarity / meaning of the WorkloadID and/or endpointID fields.

@fasaxc Is this something you (or @matthewdupre) have bandwidth to tackle, and how long would it take?  @robbrockbank is planning on a new `calico/node` release this week and we'd like to get a fix for this in.

**Comment by tomdee** [comment]
@caseydavenport Will this just work now that felix is fixed?

**Comment by caseydavenport** [comment]
@tomdee Yes.  Requires re-testing with `calico/node:v0.21.0`.

**Comment by caseydavenport** [comment]
OK - tested and working with v0.21.0
