### ISSUE TITLE
Wrong profiles applied when using k8s and no policy

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-cni#154]
Looks like the Go CNI plugin assigns the wrong profiles when _not_ using `policy: {"type": "k8s"}`.

Namely: https://github.com/projectcalico/calico-cni/blob/master/k8s/k8s.go#L40

The above line always uses a per-namespace profile, which won't exist when not using the policy-controller.  This means Felix will drop all traffic to / from that pod.

The fix here is either:
1) Don't use the `k8s_ns.name` profile when policy is disabled, just default to the CNI network name profile.
2) Use the `k8s_ns.name` profile, but ensure that it is created when policy is disabled.

I _think_ my preference is for the second (though haven't though about it a lot), since it is more flexible for users who might want to do per-namespace policy manually / out-of-band from k8s.  The profile could, by default, just pass to the next profile (which should be the CNI network name profile anyway), which would allow people to do per-namespace and per-cluster policy.

@tomdee thoughts?

**Comment by caseydavenport** [comment]
Another benefit of the latter is that, if policy is later added to the cluster, existing endpoints will already belong to the profiles used for policy (right now the policy-controller assumes it is the responsibility of the CNI plugin to make sure the endpoints are in the right profiles).

**Comment by tomdee** [comment]
I thought Option 1 was the design we'd agreed previously, which would be an easy fix - https://github.com/projectcalico/calico-cni/compare/master...tomdee:k8s-no-policy?expand=1

**Comment by caseydavenport** [comment]
Yeah, it's certainly simpler, and what the previous behavior was.  Let's go with that.

**Comment by tomdee** [comment]
Fixed by #157
