### ISSUE TITLE
Update configuration.md to include config for secure etcd

### ISSUE THREAD

**Issue by TamalSaha** [projectcalico/calico-cni#159]
We are running etcd on DigitalOcean. So, we need to secure etcd endpoints via tls auth. Here is the pr https://github.com/projectcalico/calico-cni/pull/113/files . Does the new Go version support connecting to secure etcd ?

I don't see anything here: https://github.com/projectcalico/calico-cni/blob/master/configuration.md#etcd-location

**Comment by caseydavenport** [comment]
@TamalSaha - Yes, it does.  That documentation needs to be updated!

See here: https://github.com/projectcalico/calico-cni/blob/master/utils/types.go#L65

**Comment by TamalSaha** [comment]
Awesome, @caseydavenport

**Comment by tomdee** [comment]
I've now updated the docs - see #158
