### ISSUE TITLE
calico-ipam should randomly allocate affinity pools

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calico-cni#165]
Not sure if this is a libcalico issue or a calico-ipam issue, but -

The python `calico-ipam` randomly selects a /26 from the available pool when the host first claims affinity. The golang `calico-ipam` always starts at `192.168.0.0/26`. Do we want to implement random host affinity like we used to?

**Comment by caseydavenport** [comment]
Yeah, I think we should.

The helper to iterate through randomly ordered blocks already exists in the code, so it should be pretty easy to make this switch.

@djosborne care to own fixing this?

**Comment by lxpollitt** [comment]
Stepping back, what's the motivation for random in the old code?

**Comment by caseydavenport** [comment]
@lxpollitt I think it's to avoid a stampede when starting up a cluster.  I remember us hitting scale issues when a lot of nodes were trying to grab the same block at the same time, and then all switch to the next block, and then the next, and so on.

**Comment by lxpollitt** [comment]
Yep, that makes sense.

**Comment by fasaxc** [comment]
Yep, that's the reason.  The old algorithm was pretty dumb too, it'd have to test each already-allocated block before trying the next one so you had O(n^2) behaviour

**Comment by gunjan5** [comment]
change is merged in `libcalico-go`
