### ISSUE TITLE
Kubernetes 1.4 is using calico-cni 1.3.1

### ISSUE THREAD

**Issue by TamalSaha** [projectcalico/calico-cni#176]
Hi,
Kubernetes 1.4 is using calico-cni 1.3.1 . Are there any plans to update it to latest GO version?
https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/calico/node.sls#L22

Also, I see that calico-ipam is not used in Kubernetes. So, how is the IPAM functionality provided in Kubernetes?

Thanks.

**Comment by fasaxc** [comment]
> Are there any plans to update it to latest GO version?

Absolutely.

> how does the IPAM functionality is provided in Kubernetes?

I believe our IPAM driver is included in the main CNI binary as a library.

**Comment by caseydavenport** [comment]
> Are there any plans to update it to latest GO version?

Yes, definitely.  See this PR (which I expect to go in to v1.4.1) which changes that install, and includes using an updated CNI version. https://github.com/kubernetes/kubernetes/pull/30598#issuecomment-246880224


> I believe our IPAM driver is included in the main CNI binary as a library.

This is correct for all versions _prior_ to v1.4.0.  Note that all new releases of the plugin will require both `calico` and `calico-ipam` installed to use the Calico IPAM functionality.

**Comment by caseydavenport** [comment]
@TamalSaha if you feel your questions are answered, could you please close out the issue? Thanks!

**Comment by TamalSaha** [comment]
Thanks for the quick response.
