### ISSUE TITLE
calico-cni doesn't work with some k8s versions

### ISSUE THREAD

**Issue by linuxerwang** [projectcalico/calico-cni#178]
It took me lots of time to make it work following the doc http://kubernetes.io/docs/getting-started-guides/ubuntu-calico/ because of the version issue.

This is the only working version combination for me:

k8s: 1.3.3
calico-node: 0.20.0/0.22.0
calicoctl: 0.20.0/0.22.0
calico: 1.3.1
calico-ipam: 1.3.1

All other combinations won't work. I tried k8s 1.3.6, calico 1.4.0/1.4.1. They all output the following error logs:

Error adding network: could not find "." plugin
Error while adding to cni lo network: could not find "." plugin
Failed to setup network for pod "ui-test-dnoey_default(f4e139bd-7cfe-11e6-9071-a01e0b032e28)" using network plugins "cni": could not find "." plugin; Skipping pod
Error syncing pod f4e0d98a-7cfe-11e6-9071-a01e0b032e28, skipping: failed to "SetupNetwork" for "ui-test-3t2n9_default" with SetupNetworkError: "Failed to setup network for pod \"ui-test-3t2n9_default(f4e0d98a-7cfe-11e6-9071-a01e0b032e28)\" using network plugins \"cni\": could not find \".\" plugin; Skipping pod"

Of course I double checked that /usr/bin/calicoctl, /usr/bin/kubectl, /usr/bin/kubelet, /opt/cni/bin/calico, /opt/cni/bin/calico-ipam are all there and have the correct sha256 sum.

Any idea why higher k8s 1.3 version would not work? What can I do to help debugging it?

Thanks.

**Comment by ae6rt** [comment]
You might need this:

https://github.com/projectcalico/calico-containers/issues/1115

**Comment by linuxerwang** [comment]
Cool! Fixed by copying loopback plugin to /opt/cni/bin.

Thanks a lot!
