### ISSUE TITLE
The cni 1.4.1 download binary is from something old, please check and fix it.

### ISSUE THREAD

**Issue by tizhou86** [projectcalico/calico-cni#181]
Hi the cni download version for 1.4.1 is broken, it's actually built from some 1.3.0+ version, since I can see the debug logs before 1.4.0, like "Querying Kubernetes API for Pod"... it takes me a day to figure it out, please fix it:-)

**Comment by tomdee** [comment]
I'm investigating this now...

**Comment by tomdee** [comment]
Can you provide a repro? 

```
wget https://github.com/projectcalico/calico-cni/releases/download/v1.4.1/calico
chmod +x calico
./calico -v
v1.4.1
```

**Comment by tizhou86** [comment]
Hi, I was following this guideline: 
https://github.com/projectcalico/calico-containers/blob/master/docs/cni/kubernetes/KubernetesIntegration.md

And I did this step:
wget -N -P /opt/cni/bin https://github.com/projectcalico/calico-cni/releases/download/v1.4.1/calico
wget -N -P /opt/cni/bin https://github.com/projectcalico/calico-cni/releases/download/v1.4.1/calico-ipam
chmod +x /opt/cni/bin/calico /opt/cni/bin/calico-ipam

And I opened debug mode in/etc/cni/net.d/10-calico.conf file and took a look at the /var/log/calico/cni/cni.log I saw something like "Querying Kubernetes API for Pod" and it's pointing to the wrong default k8s api server endpoint.

I supposed you guys just fix this in:
https://github.com/projectcalico/calico-cni/pull/108/files

**Comment by tizhou86** [comment]
Now i'm using 1.4.2 binary and it's ok.
