### ISSUE TITLE
Can not access external websites from pods on kubernetes/calico

### ISSUE THREAD

**Issue by linuxerwang** [projectcalico/calico-cni#193]
Hi, all

I set up a cluster following http://kubernetes.io/docs/getting-started-guides/ubuntu-calico/. Most of the functionality of Kubernetes works well (pods get IPs correctly, pods can communicate with other pods, DNS works fine, DNS resolving works fine.), the only problem is that it can not connect to outside websites from pods. From within pods, it can ping host nodes correctly, but ping to machines in the same network but not in k8s cluster hangs forever.

The versions I am using:
```
Ubuntu: 16.04.1
k8s: 1.3.6
calico-node: 0.22.0
calico-cni: 1.4.2
cni plugin (loopback): 0.3.0
```
calicoctl status shows the correct node-to-node mesh addrs. Outside of k8s, nodes can ping other nodes and machines not in k8s cluster.

The route table in pod:
```
# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         169.254.1.1     0.0.0.0         UG    0      0        0 eth0
169.254.1.1     0.0.0.0         255.255.255.255 UH    0      0        0 eth0

# cat /etc/resolv.conf 
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.10.0.10 # <--- 10.10.0.10 is the dns cluster IP I set.
options ndots:5
```
My pod IP range is 172.10.0.0/16, and all pods' IPs are correctly assigned. I am not sure about the 169.254.1.1 in route table, but pods can talk to other pods (172.10.0.0/16) without problem. Communicating through service IP is also ok.  But any ping to machines out of k8s or public domains will just hang forever.

Where should I debug from? I can provide more details if needed.

Thanks!

**Comment by fasaxc** [comment]
@linuxerwang Where are you running kubernetes? On-premises, or in a public cloud?  What does `calicoctl pool show` give?

**Comment by linuxerwang** [comment]
Thank you, fasaxc.

The k8s cluster is running on a few bare metal machines.

------------------

calicoctl pool show
+---------------+---------+
|   IPv4 CIDR   | Options |
+---------------+---------+
| 172.10.0.0/16 |         |
+---------------+---------+
+--------------------------+---------+
|        IPv6 CIDR         | Options |
+--------------------------+---------+
| fd80:24e2:f998:72d6::/64 |         |
+--------------------------+---------+

----------------

calicoctl status

calico-node container is running. Status: Up 14 hours
Running felix version 1.4.0

IPv4 BGP status
IP: 192.168.99.81    AS Number: 64511 (inherited)
+---------------+-------------------+-------+----------+-------------+
|  Peer address |     Peer type     | State |  Since   |     Info    |
+---------------+-------------------+-------+----------+-------------+
| 192.168.99.82 | node-to-node mesh |   up  | 23:56:05 | Established |
| 192.168.99.83 | node-to-node mesh |   up  | 23:57:32 | Established |
| 192.168.99.85 | node-to-node mesh |   up  | 23:59:09 | Established |
| 192.168.99.84 | node-to-node mesh |   up  | 00:02:23 | Established |
| 192.168.99.86 | node-to-node mesh |   up  | 00:20:01 | Established |
| 192.168.99.87 | node-to-node mesh |   up  | 00:23:02 | Established |
+---------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 address configured.

**Comment by linuxerwang** [comment]
And the calico etcd keys, might be helpful to debug:

/calico
/calico/v1
/calico/v1/ipam
/calico/v1/ipam/v4
/calico/v1/ipam/v4/pool
/calico/v1/ipam/v4/pool/172.10.0.0-16
/calico/v1/ipam/v6
/calico/v1/ipam/v6/pool
/calico/v1/ipam/v6/pool/fd80:24e2:f998:72d6::-64
/calico/v1/config
/calico/v1/config/LogFilePath
/calico/v1/config/IpInIpEnabled
/calico/v1/config/ReportingIntervalSecs
/calico/v1/config/ClusterGUID
/calico/v1/config/InterfacePrefix
/calico/v1/config/LogSeverityFile
/calico/v1/config/LogSeverityScreen
/calico/v1/Ready
/calico/v1/host
/calico/v1/host/gallium
/calico/v1/host/gallium/bird_ip
/calico/v1/host/gallium/workload
/calico/v1/host/gallium/workload/k8s
/calico/v1/host/gallium/workload/k8s/default.vexillary-test-3525235512-ktp4d
/calico/v1/host/gallium/workload/k8s/default.vexillary-test-3525235512-ktp4d/endpoint
/calico/v1/host/gallium/workload/k8s/default.vexillary-test-3525235512-ktp4d/endpoint/eth0
/calico/v1/host/gallium/workload/k8s/default.busybox
/calico/v1/host/gallium/workload/k8s/default.busybox/endpoint
/calico/v1/host/gallium/workload/k8s/default.busybox/endpoint/eth0
/calico/v1/host/gallium/workload/k8s/default.vexillary-demo-65393410-okc17
/calico/v1/host/gallium/workload/k8s/default.vexillary-demo-65393410-okc17/endpoint
/calico/v1/host/gallium/workload/k8s/default.vexillary-demo-65393410-okc17/endpoint/eth0
/calico/v1/host/gallium/config
/calico/v1/host/gallium/config/DefaultEndpointToHostAction
/calico/v1/host/gallium/config/marker
/calico/v1/host/aluminum
/calico/v1/host/aluminum/bird_ip
/calico/v1/host/aluminum/workload
/calico/v1/host/aluminum/config
/calico/v1/host/aluminum/config/marker
/calico/v1/host/aluminum/config/DefaultEndpointToHostAction
/calico/v1/host/bromine
/calico/v1/host/bromine/config
/calico/v1/host/bromine/config/DefaultEndpointToHostAction
/calico/v1/host/bromine/config/marker
/calico/v1/host/bromine/bird_ip
/calico/v1/host/bromine/workload
/calico/v1/host/bromine/workload/k8s
/calico/v1/host/bromine/workload/k8s/default.vexillary-demo-65393410-lozz8
/calico/v1/host/bromine/workload/k8s/default.vexillary-demo-65393410-lozz8/endpoint
/calico/v1/host/bromine/workload/k8s/default.vexillary-demo-65393410-lozz8/endpoint/eth0
/calico/v1/host/carbon
/calico/v1/host/carbon/bird_ip
/calico/v1/host/carbon/workload
/calico/v1/host/carbon/workload/k8s
/calico/v1/host/carbon/workload/k8s/default.hey
/calico/v1/host/carbon/workload/k8s/default.hey/endpoint
/calico/v1/host/carbon/workload/k8s/default.hey/endpoint/eth0
/calico/v1/host/carbon/config
/calico/v1/host/carbon/config/DefaultEndpointToHostAction
/calico/v1/host/carbon/config/marker
/calico/v1/host/europium
/calico/v1/host/europium/bird_ip
/calico/v1/host/europium/workload
/calico/v1/host/europium/config
/calico/v1/host/europium/config/DefaultEndpointToHostAction
/calico/v1/host/europium/config/marker
/calico/v1/host/dubnium
/calico/v1/host/dubnium/bird_ip
/calico/v1/host/dubnium/workload
/calico/v1/host/dubnium/config
/calico/v1/host/dubnium/config/DefaultEndpointToHostAction
/calico/v1/host/dubnium/config/marker
/calico/v1/host/fluorine
/calico/v1/host/fluorine/bird_ip
/calico/v1/host/fluorine/workload
/calico/v1/host/fluorine/workload/k8s
/calico/v1/host/fluorine/workload/k8s/default.vexillary-demo-65393410-gpshj
/calico/v1/host/fluorine/workload/k8s/default.vexillary-demo-65393410-gpshj/endpoint
/calico/v1/host/fluorine/workload/k8s/default.vexillary-demo-65393410-gpshj/endpoint/eth0
/calico/v1/host/fluorine/workload/k8s/default.vexillary-test-3525235512-kxe8l
/calico/v1/host/fluorine/workload/k8s/default.vexillary-test-3525235512-kxe8l/endpoint
/calico/v1/host/fluorine/workload/k8s/default.vexillary-test-3525235512-kxe8l/endpoint/eth0
/calico/v1/host/fluorine/workload/k8s/kube-system.kubernetes-dashboard-4151927145-564c0
/calico/v1/host/fluorine/workload/k8s/kube-system.kubernetes-dashboard-4151927145-564c0/endpoint
/calico/v1/host/fluorine/workload/k8s/kube-system.kubernetes-dashboard-4151927145-564c0/endpoint/eth0
/calico/v1/host/fluorine/workload/k8s/kube-system.kube-dns-v20-q6tca
/calico/v1/host/fluorine/workload/k8s/kube-system.kube-dns-v20-q6tca/endpoint
/calico/v1/host/fluorine/workload/k8s/kube-system.kube-dns-v20-q6tca/endpoint/eth0
/calico/v1/host/fluorine/config
/calico/v1/host/fluorine/config/marker
/calico/v1/host/fluorine/config/DefaultEndpointToHostAction
/calico/v1/policy
/calico/v1/policy/profile
/calico/v1/policy/profile/calico-k8s-network
/calico/v1/policy/profile/calico-k8s-network/tags
/calico/v1/policy/profile/calico-k8s-network/labels
/calico/v1/policy/profile/calico-k8s-network/rules
/calico/ipam
/calico/ipam/v2
/calico/ipam/v2/handle
/calico/ipam/v2/handle/default.hey
/calico/ipam/v2/handle/default.busybox
/calico/ipam/v2/handle/default.vexillary-demo-65393410-gpshj
/calico/ipam/v2/handle/default.vexillary-demo-65393410-okc17
/calico/ipam/v2/handle/default.vexillary-test-3525235512-ktp4d
/calico/ipam/v2/handle/kube-system.kubernetes-dashboard-4151927145-564c0
/calico/ipam/v2/handle/kube-system.kube-dns-v20-q6tca
/calico/ipam/v2/handle/default.vexillary-demo-65393410-lozz8
/calico/ipam/v2/handle/default.vexillary-test-3525235512-kxe8l
/calico/ipam/v2/host
/calico/ipam/v2/host/bromine
/calico/ipam/v2/host/bromine/ipv4
/calico/ipam/v2/host/bromine/ipv4/block
/calico/ipam/v2/host/bromine/ipv4/block/172.10.182.192-26
/calico/ipam/v2/host/bromine/ipv6
/calico/ipam/v2/host/bromine/ipv6/block
/calico/ipam/v2/host/carbon
/calico/ipam/v2/host/carbon/ipv4
/calico/ipam/v2/host/carbon/ipv4/block
/calico/ipam/v2/host/carbon/ipv4/block/172.10.94.192-26
/calico/ipam/v2/host/carbon/ipv6
/calico/ipam/v2/host/carbon/ipv6/block
/calico/ipam/v2/host/europium
/calico/ipam/v2/host/europium/ipv4
/calico/ipam/v2/host/europium/ipv4/block
/calico/ipam/v2/host/europium/ipv6
/calico/ipam/v2/host/europium/ipv6/block
/calico/ipam/v2/host/dubnium
/calico/ipam/v2/host/dubnium/ipv6
/calico/ipam/v2/host/dubnium/ipv6/block
/calico/ipam/v2/host/dubnium/ipv4
/calico/ipam/v2/host/dubnium/ipv4/block
/calico/ipam/v2/host/fluorine
/calico/ipam/v2/host/fluorine/ipv4
/calico/ipam/v2/host/fluorine/ipv4/block
/calico/ipam/v2/host/fluorine/ipv4/block/172.10.165.0-26
/calico/ipam/v2/host/fluorine/ipv6
/calico/ipam/v2/host/fluorine/ipv6/block
/calico/ipam/v2/host/gallium
/calico/ipam/v2/host/gallium/ipv4
/calico/ipam/v2/host/gallium/ipv4/block
/calico/ipam/v2/host/gallium/ipv4/block/172.10.222.64-26
/calico/ipam/v2/host/gallium/ipv6
/calico/ipam/v2/host/gallium/ipv6/block
/calico/ipam/v2/host/aluminum
/calico/ipam/v2/host/aluminum/ipv4
/calico/ipam/v2/host/aluminum/ipv4/block
/calico/ipam/v2/host/aluminum/ipv6
/calico/ipam/v2/host/aluminum/ipv6/block
/calico/ipam/v2/assignment
/calico/ipam/v2/assignment/ipv4
/calico/ipam/v2/assignment/ipv4/block
/calico/ipam/v2/assignment/ipv4/block/172.10.165.0-26
/calico/ipam/v2/assignment/ipv4/block/172.10.182.192-26
/calico/ipam/v2/assignment/ipv4/block/172.10.94.192-26
/calico/ipam/v2/assignment/ipv4/block/172.10.222.64-26
/calico/bgp
/calico/bgp/v1
/calico/bgp/v1/global
/calico/bgp/v1/global/as_num
/calico/bgp/v1/global/node_mesh
/calico/bgp/v1/host
/calico/bgp/v1/host/bromine
/calico/bgp/v1/host/bromine/ip_addr_v4
/calico/bgp/v1/host/bromine/ip_addr_v6
/calico/bgp/v1/host/carbon
/calico/bgp/v1/host/carbon/ip_addr_v4
/calico/bgp/v1/host/carbon/ip_addr_v6
/calico/bgp/v1/host/europium
/calico/bgp/v1/host/europium/ip_addr_v4
/calico/bgp/v1/host/europium/ip_addr_v6
/calico/bgp/v1/host/dubnium
/calico/bgp/v1/host/dubnium/ip_addr_v4
/calico/bgp/v1/host/dubnium/ip_addr_v6
/calico/bgp/v1/host/fluorine
/calico/bgp/v1/host/fluorine/ip_addr_v6
/calico/bgp/v1/host/fluorine/ip_addr_v4
/calico/bgp/v1/host/gallium
/calico/bgp/v1/host/gallium/ip_addr_v4
/calico/bgp/v1/host/gallium/ip_addr_v6
/calico/bgp/v1/host/aluminum
/calico/bgp/v1/host/aluminum/ip_addr_v4
/calico/bgp/v1/host/aluminum/ip_addr_v6

**Comment by fasaxc** [comment]
If you're running on bare-metal then you either need to peer with your routers to get external connectivity or you need to enabled the `--nat-outgoing` flag on your IP pool.
```
calicoctl pool add 172.10.0.0/16 --nat-outgoing
```
should do the trick.

**Comment by linuxerwang** [comment]
Great! It worked like a charm!

Thank you so much, fasaxc!
