### ISSUE TITLE
Support alternate CNI plugin dir for hosted install.

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-cni#198]
Some hosts mount `/opt/cni/bin` as read-only, which causes the install script to fail.

Would be nice if we allow for an alternative to be passed as a backup in case that doesn't work.

**Comment by caseydavenport** [comment]
To be clear - this is already supported just fine.  You just need to tweak the hosted install manifest to  point at the directory on the host you'd like to use.

**Comment by tomdee** [comment]
Fixed by #233
