### ISSUE TITLE
Confusing error message from calico-ipam

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calico-cni#25]
I'm not sure what the code or details mean. But the main issue is the `rc=44` which should (maybe) match the code:300

```
sudo CNI_PATH=$CNI_PATH ./priv-net-run.sh ifconfig
2016-01-05 14:18:57,077 13648 [98b3e165] ERROR IPAM plugin error (rc=44): {"msg": "No IPv4 addresses available in pool", "cniVersion": "0.1.0", "code": 300, "details": ""}

2016-01-05 14:18:57,078 13648 [98b3e165] ERROR CNI Error:
{
  "msg": "No IPv4 addresses available in pool", 
  "cniVersion": "0.1.0", 
  "code": 300, 
  "details": ""
}
calico-k8s-network : error executing ADD: No IPv4 addresses available in pool
```

**Comment by tomdee** [comment]
@caseydavenport I think we cleaned all this up? Can this issue be closed?

**Comment by caseydavenport** [comment]
I don't think we got to the bottom of why this was happening.

**Comment by tomdee** [comment]
I thought the issue was just tracking the strangeness of the error message. I'm pretty sure this happened because there were no pools defined.

**Comment by caseydavenport** [comment]
My understanding was the disconnect between the error codes returned and logged out (44 vs 300).

The message itself seems fine.

**Comment by tomdee** [comment]
@caseydavenport We will still hit this now that we don't call out to the calico-ipam binary?

**Comment by caseydavenport** [comment]
Probably not, though it likely still exists in our IPAM plugin.

Will close for now as not reproducible since I haven't seen it since that one time.

**Comment by tomdee** [comment]
I've just seen this error
`2016-03-09 11:38:54,207 1666 [964e2681] ERROR IPAM plugin error (rc=100): {"msg": "Failed to assign IP address", "code": 100, "details": "192.168.2.5 is already assigned in block 192.168.2.0/26"}`

The rc and the code match up so this is _probably_ OK.

**Comment by caseydavenport** [comment]
Cool.  Should we be worried that we've tried to assign the same address twice?
