### ISSUE TITLE
pod -> svc traffic times out with kube-proxy --proxy-mode=usermode

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-cni#38]
Reported over slack:

> tobad [1:04 PM] 
> So I've now managed to get calico to work with kubernets for everything except pod -> svc. I can call node - svc and pod -> pod but not pod -> svc
> tobad [1:20 PM] 
> If I connect with netcat I just get a connection timedout
> tobad ​[1:22] 
> Hmm seems if I switch to iptables mode for kube-proxy then it works.. will try to set cluster to use iptables and see if everything works

Do we still support usermode? If so, we need to dig in, otherwise we need to document that iptables is the only one we support.

**Comment by caseydavenport** [comment]
We **should** still work with the usespace proxy so long as no policy is enabled.  We haven't done any testing against the userspace proxy, and should be recommending people away from userspace when possible, as it has significantly worse performance and changes the source IP of service bound traffic.

**Comment by caseydavenport** [comment]
https://github.com/projectcalico/calico-containers/pull/780 fixed this.
