### ISSUE TITLE
Pod can't reach itself via a service IP

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-cni#40]
Reported by tobad on Slack:

>While using calico I'm having issues where a Pod connects back to itself via a service POD1 -> SVC1 -> POD1. For non calico networking it seems like the kubelet turns on Reflective Relay (Hairpin) mode on the interfaces but when checking the calicXXX interfaces this isn't turned on.

Related Kubernetes issue: https://github.com/kubernetes/kubernetes/issues/13375 (but that is using bridge-based networking).

**Comment by tobad357** [comment]
This causing issues with both Kafka that connects back to it self via the advertised host name and Apache Drill which does a similar thing when scheduling jobs to drill bits.

**Comment by caseydavenport** [comment]
Interesting.  From a very brief investigation, "hairpin_mode" as discussed in the linked issue seems only to apply to bridge devices, which Calico doesn't use.  I'll have to dig deeper on this - maybe there is an equivalent to "hairpin_mode" for non-bridged devices that I haven't found yet. 

Grabbing a couple related iptables rules from my local cluster, it looks like Kubernetes will perform SNAT on traffic from pods that try to access themselves via a service.
```
-A KUBE-SERVICES -d 10.100.0.211/32 -p tcp -m comment --comment "default/nginx: cluster IP" -m tcp --dport 80 -j KUBE-SVC-4N57TFCL4MD7ZTDA
-A KUBE-SVC-4N57TFCL4MD7ZTDA -m comment --comment "default/nginx:" -j KUBE-SEP-AO3QCNJDMIL7H3R6
-A KUBE-SEP-AO3QCNJDMIL7H3R6 -s 192.168.0.32/32 -m comment --comment "default/nginx:" -j MARK --set-xmark 0x4d415351/0xffffffff
-A KUBE-SEP-AO3QCNJDMIL7H3R6 -p tcp -m comment --comment "default/nginx:" -m tcp -j DNAT --to-destination 192.168.0.32:80
-A POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x4d415351 -j MASQUERADE
```

**Comment by tobad357** [comment]
Yes I'm seeing the SNAT as well but doesn't seem to be picking up the traffic when using Calico
Will continue to look at it

For anyone with the same issue (until fixed).
We have worked around this by adding the service name to the pods hosts file and pointing it to the local pod IP instead. Not ideal but works

**Comment by fasaxc** [comment]
@caseydavenport They're using a MARK to pass the information from the KUBE-SEP chain to the POSTROUTING chain.  Is the KUBE-SEP chain called from the PREROUTING chain?  If so, I bet we're clobbering the mark in the FORWARD chain, which is between those two.

That's going to be problematic because we need at least one bit of the mark (which is only 32bits).  The mark supports a mask so we could use the lower bits and kube-proxy the higher bits but that may require modifications to kube-proxy (and felix) to support that.

**Comment by thockin** [comment]
There's a fix in kube 1.2 for us to only use a single bit of the mark.

**Comment by caseydavenport** [comment]
Corresponding fix for Calico is in [Felix v1.3](https://github.com/projectcalico/calico/releases) and thus in [calico-containers v0.17.0](https://github.com/projectcalico/calico-containers/releases/tag/v0.17.0)

I can close this guy out once I get around to testing it all together.

**Comment by caseydavenport** [comment]
I've re-tested this using calico-containers v0.17.0 and Kubernetes v1.2.0-alpha.8 and it now works.

**Comment by fasaxc** [comment]
@tobad357 retested with v0.17.0 and k8s 1.2 beta.0 with success.
