### ISSUE TITLE
Support certificate based authentication for experimental policy

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-cni#42]
@euprogramador graciously added this feature to the `calico-kubernetes` plugin here: https://github.com/projectcalico/calico-kubernetes/pull/128

Should be a quick one to add to the experimental policy support in the CNI plugin.

**Comment by wienczny** [comment]
Any progress on this?

**Comment by caseydavenport** [comment]
I don't think anyone has started on this yet.  It shouldn't be a particularly complicated change.

I'll see if I can set aside some time for this soon.  We're of course always open to contributions :)

**Comment by euprogramador** [comment]
I was in recess from work and how do contributions in work break, had not developed anything, I'll start developing ...

**Comment by caseydavenport** [comment]
This is in v1.3.0 for the `k8s` policy driver.  There aren't plans to do this for the `k8s-annotations` driver.
