### ISSUE TITLE
Support authentication with ETCD

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-cni#43]
calico-containers supports this as of https://github.com/projectcalico/calico-containers/pull/654/files

The plugin should support also certificate authentication with `etcd`.

**Comment by Calpicow** [comment]
The documentation was lost from the CNI migration, but I believe it's already supported via

```
ETCD_SCHEME
ETCD_AUTHORITY
ETCD_CA_CERT_FILE
ETCD_CERT_FILE
ETCD_KEY_FILE
```

**Comment by caseydavenport** [comment]
Yes, it is quite likely that this already works and just falls out :)

I think this issue is mostly testing / documentation rather than writing any code.

**Comment by euprogramador** [comment]
i have tested, this enviroment vars is work

**Comment by caseydavenport** [comment]
Great :)
