### ISSUE TITLE
Invalid CIDR address

### ISSUE THREAD

**Issue by Calpicow** [projectcalico/calico-cni#58]
Running Kubernetes v1.2.0-alpha.8 with Docker 1.10 and calico-cni v1.0.2. It seems that my pods aren't always reachable. Below are the only error messages I could find.

Not reachable:
```
Mar 03 04:13:31 ip-100-64-32-135.*** kubelet[10981]: E0303 04:13:31.355037   10981 manager.go:293] NetworkPlugin cni failed on the status hook for pod 'ubuntu' - invalid CIDR address:
2016-03-03 04:13:31,254 12010 [default/ubuntu] INFO Created Calico endpoint with IP address(es) [IPNetwork('192.168.1.1/32')]
```

Reachable:
```
Mar 03 04:24:21 ip-100-64-32-135.*** kubelet[10981]: E0303 04:24:21.571114   10981 manager.go:293] NetworkPlugin cni failed on the status hook for pod 'ubuntu' - invalid CIDR address: Device "eth0" does not exist.
2016-03-03 04:24:21,897 20470 [default/ubuntu] INFO Created Calico endpoint with IP address(es) [IPNetwork('192.168.1.2/32')]
```

**Comment by caseydavenport** [comment]
Hmm... I'd be interested in seeing the CNI plugin logs in `/var/log/calico/cni` (with debug logging enabled).

I'd also be interested in the output of `ip link show` or `ifconfig` from within the containers.

I've seen Kubernetes sometimes emit `invalid CIDR address: Device "eth0" does not exist.` around pod startup.  I think it is a race where the container is not fully networked yet, while Kubernetes still tries to get the eth0 address.

**Comment by Calpicow** [comment]
Closing until I could consistently reproduce.
