### ISSUE TITLE
Host/profile/endpoint/IP garbage collection

### ISSUE THREAD

**Issue by Calpicow** [projectcalico/calico-cni#59]
There are artifacts left behind when a node is rebooted/terminated. They should be routinely cleaned up.

This may also cause a pod to have the wrong profile. It can be reproduced with the following:

1. Create pod, policy `<namespace>_<pod name>` created
2. Terminate machine the pod is running in
3. Recreate pod with different policy, policy `<namespace>_<pod name>` already exists: apply old policy to endpoint

**Comment by caseydavenport** [comment]
Yes, this is definitely a problem.  

When a node goes down, Calico doesn't get notifications from Kubernetes that the pods on that node are no longer running, leading to stale endpoints being left in the Calico data store and leaking IP allocations.

Some code was just merged to master to help address this, as seen in this branch: https://github.com/projectcalico/calico-cni/blob/master/calico.py#L187

It notices when a pod with the same namespace/name has been re-created and cleans up any old Calico data (endpoint, IP) before configuring the new pod's networking.

We should probably be cleaning up the profile in this case as well - I think this would solve the problem you're seeing.

**Comment by caseydavenport** [comment]
Should be fixed here: https://github.com/projectcalico/calico-cni/pull/61
