### ISSUE TITLE
Support running CNI plugin in a container

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calico-cni#62]
Using `rkt fly` it should be possible to run the CNI plugin in a container. 

This might just be a test/document issue...

**Comment by caseydavenport** [comment]
@tomdee Take a look at this guy: https://github.com/containernetworking/cni/issues/284

**Comment by caseydavenport** [comment]
We ship the plugins in a container now - I think it's just up to the orchestrators / cni spec to define running a container for CNI execution.

@tomdee  re-open if you think there is more for us to do on this.
