### ISSUE TITLE
Remove dependency on Docker client to determine NetworkMode

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-cni#68]
The CNI plugin currently calls out to the Docker client to check if NetworkMode == Host.

It needed to do this because Kubernetes was calling the CNI plugin on host networked pods, and the plugin can't do anything in this case.  See here: https://github.com/kubernetes/kubernetes/issues/19508

However, as of https://github.com/kubernetes/kubernetes/pull/20019, the CNI plugin won't get called and won't need to perform this check.

This behavior breaks using the Calico CNI plugin with rkt under Kubernetes.

Note that this will not be compatible with Kubernetes v1.1 releases.

**Comment by caseydavenport** [comment]
This is the bit of code: https://github.com/projectcalico/calico-cni/blob/master/calico_cni/container_engines.py#L44

**Comment by tomdee** [comment]
This is removed in latest master code
