### ISSUE TITLE
CNI plugin doesn't support having the hostname configured

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calico-cni#79]
It will only use a hostname of `socket.gethostname()` but hosts might be created with different names.

**Comment by caseydavenport** [comment]
socket.gethostname() does respect the HOSTNAME environment variable I believe, which means you can configure the kubelet process with the HOSTNAME env variable to use a different hostname in the CNI plugin.

Perhaps we want to make this configurable in the network config file for ease?

**Comment by tomdee** [comment]
I tried this out and it doesn't work. I started the kubelet with a different HOSTNAME environment but I still got an error from the CNI plugin `Error syncing pod, skipping: BGP configuration for host w2 not found.`

I think this should be configurable.

**Comment by caseydavenport** [comment]
Huh, wonder where I got that idea from then...  Let's make it configurable.
