### ISSUE TITLE
Should default to logging to stderr?

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calico-cni#80]
CNI spec says
`In addition, stderr can be used for unstructured output such as logs.`

So not sure why we need to log to file at all? Or are our logs too noisy to have the kubelet log them all?

**Comment by caseydavenport** [comment]
I believe we already log to stderr.

There is still value in logging to file in terms of putting all the Calico logs in one place, and for diags collection.  Though, we should probably add kubelet diags collection to `calicoctl` anyway.
