### ISSUE TITLE
CNI plugin configures incorrect endpoint data in felix when using non Calico IPAM

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calico-cni#92]
When using the `host-local` IPAM plugin with the calico CNI plugin, the wrong endpoint information is written. e.g. 
```
{"name": "cali22d2946604b", "labels": {}, "state": "active", "ipv6_nets": [], "mac": "de:88:76:04:7b:df", "ipv4_nets": ["10.0.0.15/8"], "profile_ids": ["net1"]}
```

The subnet of the ipv4_nets should be /32. The correct netmask is used on the interface in the container, it's just the etcd data that's wrong. I'm not sure what the impact of thss is without more testing and looking through the felix code.

**Comment by caseydavenport** [comment]
Presumably this is because the `host-local` IPAM is returning that prefix length, rather than the Calico CNI plugin generating that?

https://github.com/projectcalico/calico-cni/blob/master/calico.py#L379

**Comment by tomdee** [comment]
Yes

**Comment by tomdee** [comment]
Fixed in master
