### ISSUE TITLE
Plugin doesn't handle multiple networks for single container correctly

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calico-cni#94]
When a second network is added, provided it's a calico network, we should just be updating the profiles and returning the existing IP address. However, we're returning the wrong IP. I think it's because of these lines
```
return {"ip4": {"ip": str(ip4.cidr)},
                "ip6": {"ip": str(ip6.cidr)}}
```
They shouldn't be return the cidr...

**Comment by caseydavenport** [comment]
I thought the plugin already returned the IP addresses that were already assigned.  Is the problem here that we return a cidr, or that the IP address itself bad?

This should be something like `192.168.0.1/32`.

Is this only a problem in conjunction with #92?

**Comment by tomdee** [comment]
Fixed in master
