### ISSUE TITLE
In calico-k8s-cluster, sometimes policy not auto-created

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-cni#97]
When I run the `start.sh` script for the GCE version of calico-k8s-cluster, sometimes the nginx-service policy is auto-created and sometimes it's not.

**Comment by caseydavenport** [comment]
@fasaxc - Yeah, I think this is a timing bug in the cloud-config in that repo.  I saw this too a while ago.  

It's _really_ hokey: https://github.com/projectcalico/calico-k8s-cluster/blob/master/gce/master-config-template.yaml#L313

**Comment by tomdee** [comment]
Not an issue in this repo
